var quotes = ["Linio havas du flankojn",
"Tre malgranda objekto - ĝia centro",
"Forlasu deziron",
"Forlasu normalajn instrukciojn",
"Akceptu konsilon",
"Akreciĝo",
"Aldonado",
"Permesu faciligon<br />(faciligo estas la forlaso de strikto)",
"Ĉiam donu al vi meritojn por havi pli ol personecon",
"Ĉiam la unuaj paŝoj",
"Bestaj bruo",
"Ĉu ekzistas sekcioj? Konsideru transirojn",
"Petu komputilan programon ripeti vian lastan agon",
"Petu homojn labori kontraŭ ilia bona jugo",
"Demandu vian korpon",
"Kunigu iujn elementojn en grupo kaj traktu la grupon",
"Reiru kelkajn paŝojn. Kion alian vi povus fari?",
"Ekvilibru la konsistecan principon kun la malkonsisteca principo",
"Estu malpura",
"Estu ekstravaganta",
"Estu malpli kritika pli ofte",
"Spiru pli profunde",
"Konstruu pontojn",
"Brulu pontojn",
"Voku vian patron kaj demandu ŝin kion fari",
"Kaskadoj",
"Ŝanĝu ambiguecojn al specifecoj",
"Ŝanĝu specifecojn al ambiguecoj",
"Ŝanĝu instrumentajn rolojn",
"Ŝanĝu nenion kaj daŭrigu per imakula konsisto",
"Infanaj voĉoj parolas",
"Infanaj voĉoj kantas",
"Klustra analizo",
"Konsideru malsamajn fadenojn",
"Konsideru transirojn",
"Konsultu aliajn promesajn fontojn",
"Konsultu aliajn ne promesajn fontojn",
"Transformu melodian elementon en ritmikan elementon",
"Kuraĝo!",
"Tranĉu gravan konekton",
"Tranĉu virtualan konekton",
"Dekoru, dekoru",
"Difinu areon kiel “sekura” kaj uzu ĝin kiel ankro",
"Priskribu la pejzaĝon en kiu tio apartenas",
"Detruu nenion",
"Forĵetu aksiomon",
"Disciplinita mem-indulgo",
"Malkonektu de deziro",
"Malkovru la receptojn kiujn vi uzas kaj forlasu ilin"];
